chests:
  iron_chest:
    name: "&f&l铁箱子"
    page: 2
    material: iron_block
    value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjdhYWRmZjlkZGM1NDZmZGNlYzZlZDU5MTljYzM5ZGZhOGQwYzA3ZmY0YmM2MTNhMTlmMmU2ZDdmMjU5MyJ9fX0=
  gold_chest:
    name: "&6&l金箱子"
    page: 4
    material: gold_block
    value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjM3Y2FlNWM1MWViMTU1OGVhODI4ZjU4ZTBkZmY4ZTZiN2IwYjFhMTgzZDczN2VlY2Y3MTQ2NjE3NjEifX19
  diamond_chest:
    name: "&b&l钻石箱子"
    page: 8
    material: diamond_block
    value: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjU4MDdjYzRjM2I2OTU4YWVhNjE1NmU4NDUxOGQ5MWE0OWM1ZjMyOTcxZTZlYjI2OWEyM2EyNWEyNzE0NSJ9fX0=
messages:
  next_page: "&a下一页"
  prev_page: "&a上一页"
  too_many_items: "&c箱子内物品超过54个!请先清理箱子内物品后再进行拆除!"
settings:
  fakeblock: hopper
storage:
  #0 = sqlite 1 = mysql
  type: 0
  #mysql 设置
  username: username
  password: pass
  host: host
  port: port
  database: database
  useSSL: false
